version: '3'
services:
  my-app:
    container_name: 'my-app'
    image: '${my-app_IMAGE}'
    ports:
      - "3000:3000"
    volumes:
      - my-app:./my-app/build/  # build files will be added at this directory
  
  nginx:
    container_name: 'nginx'
    image: '${NGINX_IMAGE}'
    ports:
      - "80:80"
    volumes:
      - my-app:/usr/share/nginx/html/my-app # Copy React App's build files to the Nginx directory

volumes:
  my-app:
  