version: '3.2'
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    #cache_from:
    #    - '${my-app_IMAGE}'
    image: '${my-app}'
    ports:
      - "3000:3000"
    volumes:
      - my-app:./my-app/build/  # build files will be added at this directory

  nginx:
    build:
     context: ./nginx
     dockerfile: Dockerfile
    #cache_from:
    #    - '${NGINX_IMAGE}'
    image: '${nginx}'
    ports:
      - "80:80"
    volumes:
      - my-app:/usr/share/nginx/html/my-app # Copy React App's build files to the Nginx directory

volumes:
   my-app: